schema_version = "1.0.0"

id = "quad_buddy"
version = "1.1.0"
name = "Quad Buddy"
tagline = "Highlights tris and n-gons and helps you fix them"
maintainer = "Ultraviolent Games"
type = "add-on"

tags = ["Mesh"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "/tests/",
]
